import FadeIn from "@/components/FadeIn";
import Link from "next/link";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({
  title: "Privacy Policy",
  description: "How ALLIET Software Labs handles the information you submit through this website's contact form and booking integration.",
  path: "/privacy-policy",
});

export default function PrivacyPolicyPage() {
  return (
    <div className="flex flex-col min-h-screen pt-32 pb-24">
      <main className="flex-grow container mx-auto px-6 max-w-3xl">
        <FadeIn>
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-primary mb-8">
            Privacy Policy
          </h1>
          <p className="text-text-secondary mb-12">Last Updated: September 29, 2026</p>

          <div className="space-y-8 text-text-secondary leading-relaxed">
            <section>
              <h2 className="text-2xl font-bold text-primary mb-4">1. Information We Collect</h2>
              <p>Based on your interaction with our website, we may collect the following information:</p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li><strong>Contact Form Data:</strong> If you submit an inquiry through our contact form, we collect your email address, the category of your inquiry, and the contents of your message.</li>
                <li><strong>Scheduling Data:</strong> If you book a meeting using our calendar integration, we collect the name, email address, and meeting details you provide during the booking process.</li>
                <li><strong>AI Assistant Messages:</strong> If you use the &ldquo;Ask ALLIET&rdquo; assistant, the messages you type and the assistant&apos;s recent replies (up to the last eight messages of the current conversation) are sent to our server and passed to our AI provider to generate an answer.</li>
                <li><strong>Technical Data:</strong> When you submit the contact form or send a message to the assistant, your IP address is held briefly in server memory to limit repeated requests. It is not stored by us or included in the messages we receive.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-primary mb-4">2. How We Use Your Information</h2>
              <p>We use the information we collect strictly to:</p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li>Respond to your inquiries and communicate with you regarding potential projects or questions.</li>
                <li>Schedule and manage meetings.</li>
                <li>Answer questions you ask the AI assistant about ALLIET Software Labs.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-primary mb-4">3. Third-Party Services</h2>
              <p>We use the following third-party services to operate this website. These services act as data processors and may process your data on our behalf:</p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li><strong>Resend:</strong> We use Resend to securely route emails submitted via our contact form.</li>
                <li><strong>Cal.com:</strong> We use Cal.com to handle meeting scheduling and calendar availability. The Cal.com booking script is only loaded from Cal.com when you interact with the booking button on our contact page. At that point Cal.com receives standard request information (such as your IP address and browser details), even if you do not complete a booking.</li>
                <li><strong>Groq:</strong> The AI assistant&apos;s answers are generated by a language model hosted by Groq. The messages described above are sent to Groq to produce each reply and are handled under Groq&apos;s own terms and privacy policy. Please don&apos;t share passwords, financial details or other sensitive personal information in the chat.</li>
                <li><strong>Vercel:</strong> Our website is hosted on Vercel, which processes standard request information (such as IP addresses) in order to deliver the site.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-primary mb-4">4. Cookies and Tracking</h2>
              <p>Our website is designed with privacy in mind:</p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li>We do not use internal tracking cookies, marketing analytics (e.g., Google Analytics), or cross-site tracking technologies.</li>
                <li>Our scheduling integration (Cal.com) may set strictly necessary functional cookies required for the booking process to work properly.</li>
                <li>The AI assistant does not use cookies or browser storage. Your conversation exists only in the open page and is cleared when you reload or close it.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-primary mb-4">5. Data Retention</h2>
              <p>We retain your contact and scheduling information only for as long as necessary to communicate with you about your inquiry, manage our working relationship, or fulfill the purposes for which it was collected.</p>
              <p className="mt-4">We do not store or log AI assistant conversations. Each message is used to generate a reply and is not saved on our servers.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-primary mb-4">6. Contact Us</h2>
              <p>If you have any questions about this Privacy Policy or wish to request information regarding your personal data, please contact us at:</p>
              <p className="mt-2">
                <strong>Email:</strong> <a href="mailto:contact@alliet.company" className="text-primary hover:underline">contact@alliet.company</a><br />
                <strong>Brand:</strong> ALLIET Software Labs
              </p>
            </section>
          </div>
        </FadeIn>
      </main>
    </div>
  );
}
